default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  adapter: postgresql
  database: postgresql://postgres:pJDO40zH7QPpNlE1wtoJ@containers-us-west-125.railway.app:6193/railway
  username: postgres
  password: pJDO40zH7QPpNlE1wtoJ
  host: containers-us-west-125.railway.app
  port: 6193
  pool: 5
